services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    image: receipe-app-api
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

    command: sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:18.1
    volumes:
      - dev-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  # product:
  #   build:
  #     context: .
  #     dockerfile: ./DockerFile.product.dev
  #   image: recipe-app-product
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./product:/product
  #     - /product/node_modules

volumes:
  dev-db-data:
